services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'books'
      MYSQL_USER: 'hugo'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/:/var/lib/mysql
