services:
  mysql:
    image: mysql:latest
    container_name: mysql_db_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: book_bdd
      MYSQL_USER: bookadmin
      MYSQL_PASSWORD: p4$$w0rd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
